version: '{build}'
image: Visual Studio 2022
configuration: Release
init:
- cmd: >-
    tzutil /s "Russian Standard Time"

    git config --global core.autocrlf input
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- ps: >-
    [XML]$xml = Get-Content "$env:APPVEYOR_PROJECT_NAME\$env:APPVEYOR_PROJECT_NAME.csproj"

    Update-AppveyorBuild -Version "$($xml.Project.PropertyGroup.Version[0]).$env:APPVEYOR_BUILD_NUMBER"

    $CommitDateTime = [datetime]::Parse($env:APPVEYOR_REPO_COMMIT_TIMESTAMP)

    $env:BuildDate = $CommitDateTime.ToString('yyyy-MM-dd')

    Write-Host "Building v$env:APPVEYOR_BUILD_VERSION dated $env:BuildDate"
build_script:
- cmd: >-
    PostBuild %APPVEYOR_PROJECT_NAME%.proj
artifacts:
- path: ..\$(appveyor_project_name)-v$(appveyor_build_version).zip
  name: AppZip
- path: ..\$(appveyor_project_name)-v$(appveyor_build_version)-src.zip
  name: SrcZip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: $(appveyor_project_name) v$(appveyor_build_version)
  description: '* $(appveyor_repo_commit_message)\n\nBuild #$(appveyor_build_number) by AppVeyor $(BuildDate)'
  auth_token:
    secure: Oyf/ccEamPwfWLPEZQlf9hPfhGGXu3Kqnmt9saeaTMH2OE6OR0tAt2JkDl/FRR9o
  artifact:
  - AppZip
  - SrcZip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: main
only_commits:
  files:
    - '*.cs'
    - '*.yml'
skip_commits:
  files:
    - docs\*
    - '**\*.md'
